/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as LagnaBastaRouteImport } from './routes/lagna-basta'
import { Route as MenRouteImport } from './routes/men'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as WomenRouteImport } from './routes/women'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const LagnaBastaRoute = LagnaBastaRouteImport.update({
  id: '/lagna-basta',
  path: '/lagna-basta',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/kids': typeof KidsRoute
  '/lagna-basta': typeof LagnaBastaRoute
  '/men': typeof MenRoute
  '/shop': typeof ShopRoute
  '/wedding': typeof WeddingRoute
  '/women': typeof WomenRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/kids': typeof KidsRoute
  '/lagna-basta': typeof LagnaBastaRoute
  '/men': typeof MenRoute
  '/shop': typeof ShopRoute
  '/wedding': typeof WeddingRoute
  '/women': typeof WomenRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/kids': typeof KidsRoute
  '/lagna-basta': typeof LagnaBastaRoute
  '/men': typeof MenRoute
  '/shop': typeof ShopRoute
  '/wedding': typeof WeddingRoute
  '/women': typeof WomenRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/kids'
    | '/lagna-basta'
    | '/men'
    | '/shop'
    | '/wedding'
    | '/women'
    | '/category/$slug'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/kids'
    | '/lagna-basta'
    | '/men'
    | '/shop'
    | '/wedding'
    | '/women'
    | '/category/$slug'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/kids'
    | '/lagna-basta'
    | '/men'
    | '/shop'
    | '/wedding'
    | '/women'
    | '/category/$slug'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  KidsRoute: typeof KidsRoute
  LagnaBastaRoute: typeof LagnaBastaRoute
  MenRoute: typeof MenRoute
  ShopRoute: typeof ShopRoute
  WeddingRoute: typeof WeddingRoute
  WomenRoute: typeof WomenRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lagna-basta': {
      id: '/lagna-basta'
      path: '/lagna-basta'
      fullPath: '/lagna-basta'
      preLoaderRoute: typeof LagnaBastaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  KidsRoute: KidsRoute,
  LagnaBastaRoute: LagnaBastaRoute,
  MenRoute: MenRoute,
  ShopRoute: ShopRoute,
  WeddingRoute: WeddingRoute,
  WomenRoute: WomenRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
